#!/bin/bash

mkdir deps && cd deps

curl -O https://www.peterkovesi.com/matlabfns/Misc/circularstruct.m
curl -O https://www.peterkovesi.com/matlabfns/Spatial/drawregionboundaries.m
curl -O https://www.peterkovesi.com/matlabfns/Spatial/finddisconnected.m
curl -O https://www.peterkovesi.com/matlabfns/Spatial/makeregionsdistinct.m
curl -O https://www.peterkovesi.com/matlabfns/Spatial/maskimage.m
curl -O https://www.peterkovesi.com/matlabfns/Spatial/mcleanupregions.m
curl -O https://www.peterkovesi.com/matlabfns/Spatial/regionadjacency.m
curl -O https://www.peterkovesi.com/matlabfns/Spatial/renumberregions.m

matlab -nodisplay -r "addpath('/deps'); savepath"